### ISSUE TITLE
Provided Linux Executables Do Not Run on Debian 12

### ISSUE THREAD

**Issue by gourdcaptain** [haileys/tangara-companion#3]
Trying to run the v0.4.0 Linux executables available in the downloads section on Debian 12 (x86-64, KDE and XFCE desktop environments installed) has the following result:
```
gourdcaptain@wiseman:~/Build$ ./tangaracompanion-linux-x86_64 
./tangaracompanion-linux-x86_64: symbol lookup error: ./tangaracompanion-linux-x86_64: undefined symbol: adw_toolbar_view_get_type, version LIBADWAITA_1_0
```
I have libadwaita installed, so I'm guessing it wants a version newer than are available on the libadwaita on Debian 12, but I don't know enough about GTK to guess further than that.

**Comment by gourdcaptain** [comment]
Trying to build it myself runs into the issue of it needing GTK4 4.11, when Debian 12 has 4.8.3. Hmm...

**Comment by gourdcaptain** [comment]
Slightly off-topic, but running the Windows version through Wine (v10.0rc2 from the WineHQ repository) doesn't work either.
![Tangara Companion v0 4 0 WINE](https://github.com/user-attachments/assets/7b492c8e-2fed-4031-80b6-126a9f09a4d8)

**Comment by malcircuit** [comment]
I'm on Debian 11 (Bullseye) with XFCE and having similar trouble with not having `libadwaita`:
```
~/Downloads » ./tangaracompanion-linux-x86_64                                                                                                   
./tangaracompanion-linux-x86_64: error while loading shared libraries: libadwaita-1.so.0: cannot open shared object file: No such file or directory
```

**Comment by haileys** [comment]
I've just cut [`v0.4.3`](https://github.com/haileys/tangara-companion/releases/tag/v0.4.3) which includes both a Flatpak bundle which should work across all Linux distros, as well as a cli tool which has far fewer dependencies and should run on a broader variety of systems.

Hope that solves it :) if not, just reopen with any extra details you have

**Comment by malcircuit** [comment]
I was able to get the latest version to install, run, and flash the firmware of my Tangara. Thank you!

For reference for anyone else that hasn't used `flatpak` before, these are the commands I used:
```
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gnome.Platform/x86_64/47
flatpak install tangaracompanion-v0.4.3-linux-x86_64.flatpak
flatpak run zone.cooltech.tangara.Companion
```
